# -*- coding: utf-8 -*-
"""Lets_code_exercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nKnu2hR_LoWFwTHLdAf-sC9I7JIdLS02

**Questão 1**

Faça um programa que peça ao usuário um número e imprima todos os números de um até o
número que o usuário informar
Exemplo: Se o usuário informar o número 5, seu programa deverá imprimir: 1 2 3 4 5.
"""

numero = int(input('Informe um número inteiro: '))

for i in range(1, numero + 1):
  print(i, end=' ')

for i in range(numero):
  print(i + 1, end=' ')

"""**Questão 2**

Crie um programa que leia um valor qualquer e apresente uma mensagem dizendo em qual
dos seguintes intervalos ([0,25], (25,50], (50,75], (75,100]) este valor se encontra. Caso o valor não
esteja em nenhum destes intervalos, deverá ser impressa a mensagem “Fora de intervalo”. Veja
alguns exemplo abaixo:
"""

numero = float(input('Informe um número: '))

if numero < 0 or numero > 100:
  print('Fora de intervalo')
elif numero <= 25:
  print('[0, 25]')
elif numero <= 50:
  print('(25, 50]')
elif numero <= 75:
  print('(50,75]')
else:
  print('(75,100]')

"""**Questão 3**

Crie uma função que recebe o valor do raio de um círculo como parâmetro e retorna o valor da
área desse círculo. Lembrando que a área de círculo é dada pela equação: A = ℼ r^2.

"""

from math import pi

def calcular_area_circulo(raio):
  return pi * raio ** 2

raio = 10 
area = calcular_area_circulo(10)

print(area)

"""**Questão 4**

Faça um programa que peça 2 números inteiros e um número real, calcule e mostre:
a) o produto entre o dobro do primeiro e a metade do segundo.
b) a soma entre o triplo do primeiro e o terceiro.
c) o terceiro elevado ao cubo
"""

primeiro = int(input('Informe um número inteiro: '))
segundo = int(input('Informe outro número inteiro: '))
terceiro = int(input('Informe um número real: '))

# a
print('\nLETRA (a)')
dobro_do_primeiro = primeiro * 2
metade_do_segundo = segundo / 2
print('(2 x N1) * (N2 / 2) =', dobro_do_primeiro * metade_do_segundo)

# b
print('\nLETRA (b)')
triplo_do_primeiro = primeiro * 3
print('(3 x N1) + N3 =', triplo_do_primeiro + terceiro)

# c
print('\nLETRA (c)')
print('N3^3 =', terceiro ** 3)

"""**Questão 5**

Vamos fazer um programa para verificar quem é o assassino de um crime. Para descobrir o
assassino, a polícia faz um pequeno questionário com 5 perguntas onde a resposta só pode ser
sim ou não:
1. Mora perto da vítima?
2. Já trabalhou com a vítima?
3. Telefonou para a vítima?
4. Esteve no local do crime?
5. Devia para a vítima?

Cada resposta sim dá um ponto para o suspeito. A polícia considera que os suspeitos com 5
pontos são os assassinos, com 4 a 3 pontos são cúmplices e 2 pontos são apenas suspeitos,
necessitando de outras investigações. Valores abaixo de 2 são liberados.
No seu programa, você deve fazer essas perguntas e, de acordo com as respostas do usuário,
você vai informar como a polícia o considera
"""

mora_perto = input('Mora perto da vítima? ').lower()
trabalhou_com = input('Já trabalhou com a vítima? ').lower()
telefonou_para = input('Telefonou para a vítima? ').lower()
esteve_no_local = input('Esteve no local do crime? ').lower()
devia_para = input('Devia para a vítima? ').lower()

pontuacao_total = 0

if mora_perto == 'sim':
  pontuacao_total += 1
if trabalhou_com == 'sim':
  pontuacao_total += 1
if telefonou_para == 'sim':
  pontuacao_total += 1
if esteve_no_local == 'sim':
  pontuacao_total += 1
if devia_para == 'sim':
  pontuacao_total += 1

if pontuacao_total == 5:
  print('Assassino! 😱')
elif pontuacao_total >= 3:
  print('Cúmplice 😨')
elif pontuacao_total == 2:
  print('Suspeito 🧐')
else:
  print('Liberado 🙌')